(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.org/packages/")
(source "melpa-stable" "http://stable.melpa.org/packages/")

(depends-on "ansi")
(depends-on "cask")
(depends-on "dash")
(depends-on "elpy")
(depends-on "epl")
(depends-on "f")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "material-theme")
(depends-on "minions")
(depends-on "multiple-cursors")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
